<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TekArch" ignored="0" name="Test" tests="2" failures="1" timestamp="06 May 2021 18:11:58 GMT" time="14.036" errors="0">
  <testcase name="@AfterMethod CloseReport" time="0.0" classname="testcases.VerifyLoginFunctionality">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at testcases.VerifyLoginFunctionality.CloseReport(VerifyLoginFunctionality.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod CloseReport -->
  <testcase name="@AfterMethod CloseReport" time="0.0" classname="testcases.VerifyLoginFunctionality">
    <skipped/>
  </testcase> <!-- @AfterMethod CloseReport -->
  <testcase name="@AfterTest tearDown" time="0.0" classname="base.BaseTest">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="VerifyLoginErrorMessage02" time="0.018" classname="testcases.VerifyLoginFunctionality">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLoginErrorMessage02 -->
  <testcase name="VerifyLoginErrorMessage01" time="13.182" classname="testcases.VerifyLoginFunctionality"/>
</testsuite> <!-- Test -->
